!python -m torch.distributed.launch --nproc_per_node=2 --master_port=12345 \
    --use_env main.py \
    --coco_path /kaggle/working/data4training \
    --batch_size 1 \
    --lr 2.5e-5 \
    --epochs 4 \
    --backbone_name small_dWr \
    --pre_trained /kaggle/working/YOLOS/deit_s_dWr_300.pth \
    --eval_size 600 \
    --init_pe_size 512 864 \
    --mid_pe_size 512 864 \
    --output_dir run \
    --wandb_project EmoticGender-Detection \
    --wandb_name yolos_ver2