python -m torch.distributed.launch --nproc_per_node=2 --master_port=12355 \
    --use_env main.py \
    --coco_path /mnt/Userdrive/tiennv/nnthanh/datasets/EmoticGender_COCO \
    --batch_size 1 \
    --lr 2.5e-5 \
    --epochs 500 \
    --backbone_name small_dWr \
    --pre_trained weights/deit_s_dWr_300.pth \
    --eval_size 600 \
    --init_pe_size 512 864 \
    --mid_pe_size 512 864 \
    --output_dir run